name: Update the common Platform.sh Repository

on:
  push:
    branches:
      - "develop"
      - "master"

jobs:
  update-platform-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Update the Platform Repo Submodule for Backend
        run: |
          # Remove the .netrc file to avoid any conflicts
          rm -f ~/.netrc

          repo_owner="os2ulf"
          repo_name="os2udoglaer-frontend"
          event_type="update-submodule"

          # Get the latest commit hash
          commit_hash=${{ github.sha }}

          # Get the branch name
          branch_name=${{ github.ref_name }}

          # Valid branches are main and develop, fail on anything else
          if [ "$branch_name" != "main" ] && [ "$branch_name" != "develop" ]; then
            echo "Invalid branch name: $branch_name"
            exit 1
          fi

          # Echo out the above variables
          echo "Commit Hash: $commit_hash"
          echo "Branch Name: $branch_name"
          echo "Repository Owner: $repo_owner"
          echo "Repository Name: $repo_name"
          echo "Event Type: $event_type"
          echo "URL: https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/103351619/dispatches"
          echo "Payload: {\"submodule\": \"frontend\", \"branch\": \"$branch_name\", \"commit\": \"$commit_hash\"}"

          # Create a client payload

          # Trigger the repository dispatch event
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST
            -H "Accept: application/vnd.github+json"
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_TOKEN }}"
            -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/103351619/dispatches
          -d '{ "ref":"$branch_name", "inputs": {\"submodule\": \"frontend\", \"branch\": \"$branch_name\", \"commit\": \"$commit_hash\"} }')

          if test $RESPONSE_CODE -ne 204; then
            echo "Response: $RESPONSE_CODE"
            exit 1
          fi
